name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Flutter (stable) and cache it
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub
